/* codigo.js - GERADO: copia literal das linhas 38 a 105 de src/quicksort_par.c,
   para as demos destacarem linha por linha. Nao editar a mao. */
window.CODIGO_QS = { inicio: 38, linhas: [
 "typedef struct {",
 "    int *v;",
 "    long lo, hi;",
 "    int orcamento;   /* quantas threads esta tarefa pode usar no total */",
 "} Tarefa;",
 "",
 "static void quicksort_par(int *v, long lo, long hi, int orcamento);",
 "",
 "static void *rotina_thread(void *arg) {",
 "    Tarefa *t = (Tarefa *)arg;",
 "    quicksort_par(t->v, t->lo, t->hi, t->orcamento);",
 "    return NULL;",
 "}",
 "",
 "static void quicksort_par(int *v, long lo, long hi, int orcamento) {",
 "    long tamanho = hi - lo + 1;",
 "    if (orcamento <= 1 || tamanho < LIMITE_PARALELO) {",
 "        quicksort_seq(v, lo, hi);           /* mesmo algoritmo da versao sequencial */",
 "        return;",
 "    }",
 "",
 "    long p = particionar(v, lo, hi);        /* v[lo..p] <= pivo <= v[p+1..hi] */",
 "    long tam_esq = p - lo + 1;",
 "",
 "    /* Reparte o orcamento proporcionalmente ao tamanho de cada lado. */",
 "    int orc_esq = (int)((double)orcamento * tam_esq / tamanho + 0.5);",
 "    if (orc_esq < 1) orc_esq = 1;",
 "    if (orc_esq > orcamento - 1) orc_esq = orcamento - 1;",
 "    int orc_dir = orcamento - orc_esq;",
 "",
 "    Tarefa esq = { v, lo, p, orc_esq };",
 "    pthread_t th;",
 "    if (pthread_create(&th, NULL, rotina_thread, &esq) != 0) {",
 "        /* Se nao conseguir criar a thread, faz tudo nesta mesma. */",
 "        quicksort_par(v, lo, p, orc_esq);",
 "        quicksort_par(v, p + 1, hi, orc_dir);",
 "        return;",
 "    }",
 "    quicksort_par(v, p + 1, hi, orc_dir);   /* thread atual cuida do lado direito */",
 "    pthread_join(th, NULL);                 /* espera o lado esquerdo terminar */",
 "}",
 "",
 "int main(int argc, char **argv) {",
 "    if (argc < 3) {",
 "        fprintf(stderr, \"Uso: %s <entrada.txt> <threads|max> [saida.txt]\\n\", argv[0]);",
 "        return 1;",
 "    }",
 "    int threads;",
 "    if (strcmp(argv[2], \"max\") == 0) threads = (int)sysconf(_SC_NPROCESSORS_ONLN);",
 "    else threads = atoi(argv[2]);",
 "    if (threads < 1) { fprintf(stderr, \"Numero de threads invalido\\n\"); return 1; }",
 "",
 "    long n;",
 "    int *v = ler_entrada(argv[1], &n);",
 "    long long soma_antes = soma_elementos(v, n);",
 "",
 "    double t0 = agora_segundos();",
 "    quicksort_par(v, 0, n - 1, threads);     /* <-- regiao medida */",
 "    double t1 = agora_segundos();",
 "",
 "    int ok = esta_ordenado(v, n);",
 "    int soma_ok = (soma_elementos(v, n) == soma_antes);",
 "    if (argc >= 4) escrever_saida(argv[3], v, n);",
 "",
 "    printf(\"pthreads,%d,%ld,%.9f,%d,%d\\n\", threads, n, t1 - t0, ok, soma_ok);",
 "    free(v);",
 "    return (ok && soma_ok) ? 0 : 2;",
 "}"
] };
